//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPL_Gateway.Cultures {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPL_Gateway.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Contact Us과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact01 {
            get {
                return ResourceManager.GetString("StrContact01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For General Enquiries Please use the enquiry form below과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact02 {
            get {
                return ResourceManager.GetString("StrContact02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Name*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact03 {
            get {
                return ResourceManager.GetString("StrContact03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email Address*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact04 {
            get {
                return ResourceManager.GetString("StrContact04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company Web Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact05 {
            get {
                return ResourceManager.GetString("StrContact05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone Number*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact06 {
            get {
                return ResourceManager.GetString("StrContact06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Enquiry*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact07 {
            get {
                return ResourceManager.GetString("StrContact07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEND ENQUIRY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact08 {
            get {
                return ResourceManager.GetString("StrContact08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alternatively, you can contact JPL Telecom by phone,
        ///email, or Live Chat during business hours.
        ///Monday to Friday, 9:00am to 5:00pm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact09 {
            get {
                return ResourceManager.GetString("StrContact09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CHAT NOW과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact10 {
            get {
                return ResourceManager.GetString("StrContact10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VISIT OUR WEBSITE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact11 {
            get {
                return ResourceManager.GetString("StrContact11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTACT JPL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContact12 {
            get {
                return ResourceManager.GetString("StrContact12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open JPL Gateway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContext01 {
            get {
                return ResourceManager.GetString("StrContext01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContext02 {
            get {
                return ResourceManager.GetString("StrContext02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting01 {
            get {
                return ResourceManager.GetString("StrDevice_setting01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET SETTINGS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting02 {
            get {
                return ResourceManager.GetString("StrDevice_setting02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE ALL SETTINGS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting03 {
            get {
                return ResourceManager.GetString("StrDevice_setting03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EQ Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting04 {
            get {
                return ResourceManager.GetString("StrDevice_setting04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting05 {
            get {
                return ResourceManager.GetString("StrDevice_setting05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frequency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting06 {
            get {
                return ResourceManager.GetString("StrDevice_setting06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APPLY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting07 {
            get {
                return ResourceManager.GetString("StrDevice_setting07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferred Softphone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting08 {
            get {
                return ResourceManager.GetString("StrDevice_setting08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beep Tone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting09 {
            get {
                return ResourceManager.GetString("StrDevice_setting09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key tone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting10 {
            get {
                return ResourceManager.GetString("StrDevice_setting10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ring alert tone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting11 {
            get {
                return ResourceManager.GetString("StrDevice_setting11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute interval time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_setting12 {
            get {
                return ResourceManager.GetString("StrDevice_setting12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Updates과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update01 {
            get {
                return ResourceManager.GetString("StrDevice_update01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update02 {
            get {
                return ResourceManager.GetString("StrDevice_update02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update03 {
            get {
                return ResourceManager.GetString("StrDevice_update03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update04 {
            get {
                return ResourceManager.GetString("StrDevice_update04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (locked) request for access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update05 {
            get {
                return ResourceManager.GetString("StrDevice_update05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available Updates과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update06 {
            get {
                return ResourceManager.GetString("StrDevice_update06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up to Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update07 {
            get {
                return ResourceManager.GetString("StrDevice_update07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferred Softphone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update08 {
            get {
                return ResourceManager.GetString("StrDevice_update08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description of update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update09 {
            get {
                return ResourceManager.GetString("StrDevice_update09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE NOW과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice_update10 {
            get {
                return ResourceManager.GetString("StrDevice_update10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice01 {
            get {
                return ResourceManager.GetString("StrDevice01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device
        ///Updates과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice02 {
            get {
                return ResourceManager.GetString("StrDevice02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device
        ///Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDevice03 {
            get {
                return ResourceManager.GetString("StrDevice03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Devices과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMain01 {
            get {
                return ResourceManager.GetString("StrMain01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMain02 {
            get {
                return ResourceManager.GetString("StrMain02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMain03 {
            get {
                return ResourceManager.GetString("StrMain03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JPL Products과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMain04 {
            get {
                return ResourceManager.GetString("StrMain04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect Your Device
        ///To Manage Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMain05 {
            get {
                return ResourceManager.GetString("StrMain05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_reset01 {
            get {
                return ResourceManager.GetString("StrPopup_reset01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to Factory Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_reset02 {
            get {
                return ResourceManager.GetString("StrPopup_reset02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will reset your device to its factory settings.
        ///Your settings cannot be recovered after resetting.
        ///Are you sure you would like to reset your device?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_reset03 {
            get {
                return ResourceManager.GetString("StrPopup_reset03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_reset04 {
            get {
                return ResourceManager.GetString("StrPopup_reset04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_reset05 {
            get {
                return ResourceManager.GetString("StrPopup_reset05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update01 {
            get {
                return ResourceManager.GetString("StrPopup_update01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update02 {
            get {
                return ResourceManager.GetString("StrPopup_update02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Once firmware is updated it cannot be returned to the previous version.
        ///This update includes the following features;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update03 {
            get {
                return ResourceManager.GetString("StrPopup_update03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to proceed with the firmware update?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update04 {
            get {
                return ResourceManager.GetString("StrPopup_update04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update05 {
            get {
                return ResourceManager.GetString("StrPopup_update05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proceed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update06 {
            get {
                return ResourceManager.GetString("StrPopup_update06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please do not disconnect the device
        ///during the update process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update07 {
            get {
                return ResourceManager.GetString("StrPopup_update07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please unplug the USB cable
        ///connected to the device and then plug it back in과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update08 {
            get {
                return ResourceManager.GetString("StrPopup_update08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update JPL Gateway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update09 {
            get {
                return ResourceManager.GetString("StrPopup_update09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Once Software is updated it cannot be returned to the previous version.
        ///This update includes the following features;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update10 {
            get {
                return ResourceManager.GetString("StrPopup_update10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to proceed with the JPL Gateway update?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPopup_update11 {
            get {
                return ResourceManager.GetString("StrPopup_update11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speakerphones과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct01 {
            get {
                return ResourceManager.GetString("StrProduct01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wired Headsets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct02 {
            get {
                return ResourceManager.GetString("StrProduct02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accessories과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct03 {
            get {
                return ResourceManager.GetString("StrProduct03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wireless Headsets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct04 {
            get {
                return ResourceManager.GetString("StrProduct04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom Leads과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct05 {
            get {
                return ResourceManager.GetString("StrProduct05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video Conferencing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct06 {
            get {
                return ResourceManager.GetString("StrProduct06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AV Cables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProduct07 {
            get {
                return ResourceManager.GetString("StrProduct07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting01 {
            get {
                return ResourceManager.GetString("StrSetting01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting02 {
            get {
                return ResourceManager.GetString("StrSetting02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting03 {
            get {
                return ResourceManager.GetString("StrSetting03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Country과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting04 {
            get {
                return ResourceManager.GetString("StrSetting04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting05 {
            get {
                return ResourceManager.GetString("StrSetting05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow push notifications과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting06 {
            get {
                return ResourceManager.GetString("StrSetting06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch JPL Gateway on startup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting07 {
            get {
                return ResourceManager.GetString("StrSetting07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow JPL Gateway to start up automatically upon login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting08 {
            get {
                return ResourceManager.GetString("StrSetting08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gateway Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting09 {
            get {
                return ResourceManager.GetString("StrSetting09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Newest Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting10 {
            get {
                return ResourceManager.GetString("StrSetting10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSetting11 {
            get {
                return ResourceManager.GetString("StrSetting11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSupport01 {
            get {
                return ResourceManager.GetString("StrSupport01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TroubleShooting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSupport02 {
            get {
                return ResourceManager.GetString("StrSupport02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Where to Buy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSupport03 {
            get {
                return ResourceManager.GetString("StrSupport03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compatibility과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSupport04 {
            get {
                return ResourceManager.GetString("StrSupport04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact Us과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSupport05 {
            get {
                return ResourceManager.GetString("StrSupport05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warranty Registration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSupport06 {
            get {
                return ResourceManager.GetString("StrSupport06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Troubleshooting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble01 {
            get {
                return ResourceManager.GetString("StrTrouble01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble02 {
            get {
                return ResourceManager.GetString("StrTrouble02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speaker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble03 {
            get {
                return ResourceManager.GetString("StrTrouble03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speaker Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble04 {
            get {
                return ResourceManager.GetString("StrTrouble04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speaker Volume :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble05 {
            get {
                return ResourceManager.GetString("StrTrouble05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microphone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble06 {
            get {
                return ResourceManager.GetString("StrTrouble06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microphone Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble07 {
            get {
                return ResourceManager.GetString("StrTrouble07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microphone Volume :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble08 {
            get {
                return ResourceManager.GetString("StrTrouble08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble09 {
            get {
                return ResourceManager.GetString("StrTrouble09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playback…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble10 {
            get {
                return ResourceManager.GetString("StrTrouble10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble11 {
            get {
                return ResourceManager.GetString("StrTrouble11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for audio device.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble12 {
            get {
                return ResourceManager.GetString("StrTrouble12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrouble13 {
            get {
                return ResourceManager.GetString("StrTrouble13", resourceCulture);
            }
        }
    }
}
